/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.1
*/

import { ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions, DeployContractResult } from "fuels";

import { Example } from "./Example";

const bytecode = decompressBytecode("H4sIAHLyzWYAA6VUTWgTQRR+iVsa8DLQVMu01aBpieBPwCI9zrJdkrotO9JLL8u2SmkPImUppeAlxx5bQe0xnhRPk+CheNqjx1wEjwEvFhrIQaHSQ/xmN9uEUANiIGTeN9/33pf33i5vF2mHKE3Rx/jhdcIU63Q0RvxU0iGlj72Vdpo9ESEXaxQspCUzDcFPiHJnD2n1vJmW500D/O/capAsKeW36Jq06jIoU6ZgZitdXfkvuq9dXRu6G9DtJTp99krK9WxGnqPcYIkybDEf+q2cKx31RceFRQMx44EgVmjlCZoP0LOC9aniWcrVNZHX1bh06kfQMK1BfCSdWjOJ+Ulu0NfnyJejjqG/jhoT0lIsWADfzAtZqq9GdWxD+1yF/6rfEllgV+FvHLnn49zZEFyKzrauwwbrKF5CHbfOAgnO8gzxk+Ig5z13GzRmZ8Mx9IIvEe0u0BTyFofk/djNK4bkfcediJOLOSOXcfZ1H+4sZw92lyiFeHPgvspXGhQIg2YFdkZsY5Y1hp7d0hh+b/unlEfvcujNRDTXUq0cnaPe1ao9XM33cPUtwT1XTWL+U5jnNPqfYbYhxu1sBT3QfkaApScX82K2TFSYnkN/tonZc+TbAnsHPnYANdf8VvEuZnMPnu4jv97PxM9+r269coHjjLvjPk9bfV7PEhy+bkqbMcx8D7kfSDOXiXbTxOwtVenbGa1PdmYLudtJfMn8ePxcgOfUGr1dUgfxzPMh8EKC4zmZnTEZ5kAvH2EOr4muvMnEzzC3qsRLTfJMxL/w/c3oCHdvwXl8FnFHE+4hEUv4kbcWvFnqQvtK3/f0o/+gT/2nflj9VO+/Non/1P+REk5KczY3dvyn68/XXzzbiF918fsu/APywhTcAAUAAA==");

export class ExampleFactory extends ContractFactory {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(bytecode, Example.abi, accountOrProvider);
  }

  static async deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<DeployContractResult<Example>> {
    const factory = new ExampleFactory(wallet);

    return factory.deploy({
      storageSlots: Example.storageSlots,
      ...options,
    });
  }
}
